# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Post.destroy_all
User.destroy_all


user1 = User.create!(first_name: 'Mr', last_name: 'Scruffy', username: 'sweets', email: 'scruffy@me.com', password: '123456', profile_img_url: 'www.photo1.com')
user2 = User.create!(first_name: 'Mrs', last_name: 'Flufflepuss', username: 'fluffy', email: 'fluffy@me.com', password: '123456', profile_img_url: 'www.photo2.com')
user3 = User.create!(first_name: 'Honey', last_name: 'Comb', username: 'honeycomb', email: 'honey@me.com', password: '123456', profile_img_url: 'www.photo3.com')
user4 = User.create!(first_name: 'Scott', last_name: 'Pick', username: 'kcip', email: 'me@me.com', password: '123456', profile_img_url: 'www.photo4.com')

post1 = Post.create!(post_title: 'First Post', post_content: 'Mlkshk authentic flannel gentrify +1, pop-up kogi four loko paleo pickled kombucha tousled craft beer four dollar toast post-ironic. Trust fund semiotics kickstarter, messenger bag church-key taiyaki raw denim drinking vinegar fam coloring book copper mug actually twee intelligentsia cliche. Chambray pug taxidermy DIY distillery shaman wayfarers pitchfork +1 jean shorts. Trust fund cred kale chips forage cornhole taiyaki, marfa everyday carry godard stumptown swag. Pinterest pitchfork hell of palo santo lumbersexual affogato coloring book migas kickstarter messenger bag fingerstache humblebrag. Celiac waistcoat hoodie 90', post_photo: 'https://images.unsplash.com/photo-1594511973112-532ca64d4f79?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80', user: user1)

post2 = Post.create!(post_title: 'Second Post', post_content: 'Hoodie snackwave pug selfies narwhal taiyaki. Freegan retro keffiyeh listicle cloud bread pork belly lyft normcore photo booth. Heirloom kogi before they sold out swag freegan. Locavore roof party typewriter, cronut unicorn slow-carb sustainable copper mug selvage crucifix master cleanse pabst. Echo park taiyaki franzen pitchfork biodiesel pabst, pug tousled post-ironic vape offal fixie shabby chic.', post_photo: 'https://images.unsplash.com/photo-1455459182396-ae46100617cb?ixlib=rb-1.2.1&auto=format&fit=crop&w=2560&q=80', user: user1)

post3 = Post.create!(post_title: 'Third Post', post_content: 'Cronut taxidermy green juice, intelligentsia unicorn actually food truck ennui you probably havent heard of them literally yr venmo cred. Iceland kinfolk meggings, etsy readymade tbh farm-to-table. Messenger bag cloud bread hella mixtape truffaut wayfarers craft beer retro church-key. Humblebrag meggings ugh lumbersexual gluten-free subway tile, +1 DIY brunch.', post_photo: 'https://images.unsplash.com/photo-1594586041212-c642fef5d1e1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', user: user1)

post4 = Post.create!(post_title: 'Fourth Post', post_content: 'Im baby iceland pickled heirloom readymade godard tote bag salvia, kickstarter scenester meh cloud bread literally affogato wolf. Bushwick forage pug, locavore lumbersexual vaporware paleo. Tousled chicharrones lyft, snackwave XOXO food truck chartreuse. Mlkshk hell of viral, etsy chia portland small batch gochujang heirloom PBR&B tbh stumptown raw denim. Swag wolf vice, direct trade hell of hexagon semiotics heirloom lumbersexual franzen. Portland echo park readymade shabby chic plaid, taiyaki keytar chicharrones. Banh mi meditation skateboard occupy food truck.
 Single-origin coffee waistcoat williamsburg church-key tumblr chartreuse mlkshk XOXO vinyl literally shoreditch whatever synth kombucha. Woke gochujang iPhone, yr freegan you probably havent heard of them cloud bread celiac. Adaptogen twee biodiesel pop-up typewriter. Mustache jean shorts chartreuse, meggings af lyft kitsch cold-pressed pabst. Readymade blue bottle air plant shabby chic tousled squid wayfarers hammock locavore.', post_photo: 'https://images.unsplash.com/photo-1594583446652-4e6ae5ce0753?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80', user: user1)

 post5 = Post.create!(post_title: 'Fifth Post', post_content: 'Swag wolf vice, direct trade hell of hexagon semiotics heirloom lumbersexual franzen. Portland echo park readymade shabby chic plaid, taiyaki keytar chicharrones. Banh mi meditation skateboard occupy food truck.
  Single-origin coffee waistcoat williamsburg church-key tumblr chartreuse mlkshk XOXO vinyl literally shoreditch whatever synth kombucha. Woke gochujang iPhone, yr freegan you probably havent heard of them cloud bread celiac. Adaptogen twee biodiesel pop-up typewriter. Mustache jean shorts chartreuse, meggings af lyft kitsch cold-pressed pabst. Readymade blue bottle air plant shabby chic tousled squid wayfarers hammock locavore.', post_photo: 'https://images.unsplash.com/photo-1532618790904-3c45e0405300?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', user: user1)

  post6 = Post.create!(post_title: 'Sixth Post', post_content: 'Fanny pack glossier yr bespoke, meh tattooed thundercats 8-bit truffaut salvia cray tousled. Marfa tumeric unicorn freegan blue bottle, af whatever. Leggings vice vape tumblr. Actually whatever austin, cloud bread sustainable messenger bag coloring book tumblr. Fingerstache poutine ugh, microdosing shaman gluten-free heirloom selvage hashtag organic hoodie pitchfork paleo. Paleo mumblecore YOLO, air plant 3 wolf moon whatever marfa edison bulb raw denim.Gluten-free intelligentsia try-hard, skateboard flannel +1 celiac messenger bag. Pinterest twee chambray, stumptown tousled schlitz health goth hexagon. Waistcoat vape seitan before they sold out flannel green juice. Activated charcoal tilde readymade biodiesel bushwick kombucha, shoreditch art party pinterest photo booth. Bushwick blue bottle godard meggings irony wolf scenester banh mi woke selfies viral marfa actually. Disrupt enamel pin air plant narwhal.Mustache thundercats activated charcoal craft beer la croix wayfarers banjo sriracha asymmetrical health goth single-origin coffee fixie. Sriracha drinking vinegar cronut etsy, put a bird on it bespoke air plant bushwick knausgaard raclette whatever pour-over. IPhone scenester lyft portland bitters, chia poutine af VHS. Plaid sartorial normcore slow-carb 90s cronut photo booth bicycle rights distillery pug lumbersexual jianbing tousled hoodie.', post_photo: 'https://images.unsplash.com/photo-1594206617938-dd62a15f51d8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', user: user1)

  post7 = Post.create!(post_title: 'Seventh Post', post_content: 'Cliac messenger bag. Pinterest twee chambray, stumptown tousled schlitz health goth hexagon. Waistcoat vape seitan before they sold out flannel green juice. Activated charcoal tilde readymade biodiesel bushwick kombucha, shoreditch art party pinterest photo booth. Bushwick blue bottle godard meggings irony wolf scenester banh mi woke selfies viral marfa actually. Disrupt enamel pin air plant narwhal.Mustache thundercats activated charcoal craft beer la croix wayfarers banjo sriracha asymmetrical health goth single-origin coffee fixie. Sriracha drinking vinegar cronut etsy, put a bird on it bespoke air plant bushwick knausgaard raclette whatever pour-over. IPhone scenester lyft portland bitters, chia poutine af VHS. Plaid sartorial normcore slow-carb 90s cronut photo booth bicycle rights distillery pug lumbersexual jianbing tousled hoodie.', post_photo: 'https://images.unsplash.com/photo-1594558312821-4dab3c475dc5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', user: user2)

  post8 = Post.create!(post_title: 'Eighth Post', post_content: 'Master cleanse air plant shoreditch asymmetrical chambray shaman put a bird on it narwhal normcore ethical blue bottle pour-over wayfarers. 90s mumblecore shabby chic scenester, blog slow-carb single-origin coffee put a bird on it iceland beard pour-over kitsch shoreditch godard. Vinyl cray listicle celiac DIY single-origin coffee you probably havent heard of them, unicorn bicycle rights. La croix sriracha tattooed lo-fi fam lumbersexual gochujang art party succulents. Swag echo park iceland 90s scenester. Cardigan taiyaki pork belly tumeric hell of cronut paleo activated charcoal next level. Forage narwhal pork belly cray kale chips DIY fingerstache, irony copper mug iPhone intelligentsia hot chicken PBR&B palo santo blog.', post_photo: 'https://images.unsplash.com/photo-1594499468121-f45e83e30df4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', user: user2)

  post9 = Post.create!(post_title: 'Ninth Post', post_content: 'Master cleanse air plant shoreditch asymmetrical chambray shaman put a bird on it narwhal normcore ethical blue bottle pour-over wayfarers. 90s mumblecore shabby chic scenester, blog slow-carb single-origin coffee put a bird on it iceland beard pour-over kitsch shoreditch godard. Vinyl cray listicle celiac DIY single-origin coffee you probably havent heard of them, unicorn bicycle rights. La croix sriracha tattooed lo-fi fam lumbersexual gochujang art party succulents. Swag echo park iceland 90s scenester. Cardigan taiyaki pork belly tumeric hell of cronut paleo activated charcoal next level. Forage narwhal pork belly cray kale chips DIY fingerstache, irony copper mug iPhone intelligentsia hot chicken PBR&B palo santo blog.', post_photo: 'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', user: user4)

  post10 = Post.create!(post_title: 'Tenth Post', post_content: 'Im baby selvage try-hard typewriter listicle bicycle rights post-ironic locavore dreamcatcher plaid art party pickled. Iceland cardigan kinfolk, poke occupy godard everyday carry blue bottle chillwave migas church-key kickstarter. Try-hard street art brooklyn vaporware master cleanse. Subway tile leggings marfa waistcoat fam next level umami offal DIY kitsch. 8-bit pickled pok pok, bicycle rights bushwick kogi glossier. Post-ironic synth kale chips, health goth disrupt listicle man bun next level pinterest truffaut mumblecore celiac cold-pressed vinyl flexitarian.
   Enamel pin knausgaard flexitarian adaptogen tilde. Everyday carry lyft williamsburg aesthetic mustache brooklyn. Pug vinyl tattooed cardigan man bun slow-carb cronut yr. +1 truffaut bicycle rights migas stumptown. Wolf leggings jean shorts, put a bird on it viral copper mug tbh migas narwhal. Literally mixtape VHS iPhone la croix bicycle rights keffiyeh, vexillologist raclette umami church-key austin asymmetrical pug mlkshk.
   Biodiesel ugh gochujang lomo, portland copper mug wolf gentrify tousled brooklyn vice pug deep v woke. Deep v gluten-free post-ironic semiotics, prism microdosing lomo put a bird on it. Fingerstache waistcoat banh mi mixtape tofu. Gochujang XOXO farm-to-table, yuccie fanny pack literally cardigan kombucha messenger bag. Chicharrones mlkshk kogi raw denim, cred beard semiotics copper mug narwhal microdosing taiyaki vice stumptown everyday carry. Godard pop-up fanny pack chia everyday carry listicle adaptogen kitsch vegan activated charcoal slow-carb offal knausgaard air plant dreamcatcher. Bitters echo park tattooed, ethical readymade twee paleo copper mug shoreditch.
   Tumblr 8-bit hashtag swag. Twee church-key jianbing hell of. Drinking vinegar food truck echo park bushwick kickstarter venmo. Air plant selvage ethical small batch listicle vice. Keffiyeh 3 wolf moon swag la croix YOLO knausgaard chicharrones. Gochujang hella biodiesel, drinking vinegar unicorn cray cold-pressed offal selvage kinfolk mixtape brooklyn.', post_photo: 'https://images.unsplash.com/photo-1594344041337-0223bd103abe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', user: user4)